ZMS-110
nodemailer/wildduck pull request #575
Opened 2023-12-15 10:01 UTC by NickOvt

## Users.js

Added all `Users` (and `Export`) API endpoints to the API docs generation

2023-12-18 09:50 UTC, andris9 requested changes

2023-12-18 09:50 UTC, andris9 commented on lib/api/users.js
> +                    internalData: booleanSchema.description('f true, then includes internalData in the response. Not shown for user-role tokens.'),
typo

2023-12-21 07:15 UTC, NickOvt commented on lib/api/users.js
> +                    internalData: booleanSchema.description('f true, then includes internalData in the response. Not shown for user-role tokens.'),
Fixed typo

2023-12-21 08:41 UTC, andris9 approved these changes

2023-12-21 08:42 UTC, merged