ZMS-109
nodemailer/wildduck pull request #597
Opened 2024-01-04 11:45 UTC by NickOvt

Try to reduce the amount of call to JSON.parse in order to improve the idle CPU performance of wildduck when a lot of connections are open. Also reduce the amount of empty emits by listeners

2024-01-04 11:58 UTC, andris9 requested changes

2024-01-05 08:26 UTC, andris9 approved these changes

2024-01-05 08:28 UTC, NickOvt commented
based on testing (4500 requests each for creating a message (has no payload) and logging out (has payload))
Performance has improved 2x-3x fold in case of no payload that is only .e and no parsing is needed.
Performance is the same or 100ns faster in case when data has the payload.

2024-01-05 08:31 UTC, merged

2024-01-05 08:35 UTC, andris9 commented
> based on testing (4500 requests each for creating a message (has no payload) and logging out (has payload)) Performance has improved 2x-3x fold in case of no payload that is only .e and no parsing is needed. Performance is the same or 100ns faster in case when data has the payload.

The no-payload version happens way more, as it is triggered any time something happens on the email account, e.g. an email is marked as seen or unseen. So if this use case gets optimized it is a great win 🏆