ZMS-119
nodemailer/wildduck pull request #613
Opened 2024-02-02 10:56 UTC by NickOvt

- Separate the API docs generation code into a separate public open-source npm package
- Import the package and use it with defined options

2024-02-02 11:04 UTC, NickOvt commented
https://github.com/zone-eu/restify-api-generate

https://www.npmjs.com/package/restifyapigenerate

2024-02-02 12:03 UTC, andris9 requested changes

2024-02-02 12:03 UTC, andris9 commented on api.js
> +            openapiVersion: '3.0.0',
Could you move this configuration structure into a separate file (json or js) where the config would be loaded from?

2024-02-02 12:03 UTC, andris9 commented on package.json
> +        "restifyapigenerate": "^1.1.0",
Could you remove the caret to keep dependency versions fixed. To upgrade deps, run `npm run update`

2024-02-05 07:54 UTC, andris9 approved these changes

2024-02-05 08:29 UTC, merged